[Mysql]
# 连接地址
Host = "59.110.137.58"
# 连接端口
Port = 3310
# 用户名
Username = "root"
# 密码
Password = "tc.524030"
# 数据库
DBName = "utils"
# 连接参数
Parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"